# Generated by Django 5.2.15 on 2026-07-10 23:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ecommerce", "0002_onlinecustomer_last_purchase_date_and_more"),
        ("products", "0002_product_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("product_view", "Product View"),
                            ("category_view", "Category View"),
                            ("search_query", "Search Query"),
                        ],
                        max_length=20,
                    ),
                ),
                ("search_term", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="view_events",
                        to="products.category",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="ecommerce.onlinecustomer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="view_events",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Event",
                "verbose_name_plural": "Customer Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerInsightSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("vip", "VIP"),
                            ("loyal", "Loyal"),
                            ("new", "New"),
                            ("at_risk", "At-Risk"),
                            ("price_sensitive", "Price-Sensitive"),
                            ("premium_shopper", "Premium Shopper"),
                            ("frequent_buyer", "Frequent Buyer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "avg_order_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("order_frequency_days", models.FloatField(blank=True, null=True)),
                (
                    "preferred_payment_method",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "preferred_shopping_time",
                    models.CharField(
                        blank=True,
                        help_text="e.g. morning/afternoon/evening/night",
                        max_length=20,
                    ),
                ),
                ("has_sufficient_data", models.BooleanField(default=False)),
                (
                    "prediction_method",
                    models.CharField(
                        choices=[
                            ("ml", "Machine Learning"),
                            ("rule_based", "Rule-Based Heuristic"),
                        ],
                        default="rule_based",
                        max_length=20,
                    ),
                ),
                (
                    "churn_risk_score",
                    models.FloatField(
                        blank=True, help_text="0.0-1.0 probability", null=True
                    ),
                ),
                (
                    "predicted_next_purchase_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "estimated_lifetime_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("ai_summary_text", models.TextField(blank=True)),
                ("recommended_product_ids", models.JSONField(blank=True, default=list)),
                ("model_version", models.CharField(default="v1", max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_snapshots",
                        to="ecommerce.onlinecustomer",
                    ),
                ),
                (
                    "favorite_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="top_customer_snapshots",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Insight Snapshot",
                "verbose_name_plural": "Customer Insight Snapshots",
                "ordering": ["-generated_at"],
            },
        ),
    ]
