# Generated by Django 5.2.15 on 2026-07-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zone_name",
                    models.CharField(
                        help_text="e.g. 'Freetown Central', 'Waterloo'",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "base_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Flat starting fee for any delivery to this zone",
                        max_digits=10,
                    ),
                ),
                (
                    "per_km_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Additional charge per kilometre",
                        max_digits=10,
                    ),
                ),
                (
                    "average_distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Manually estimated typical delivery distance for this zone. Used by calculate_fee() when no live distance is supplied. This is the field a future mapping/distance API would replace or override on a per-order basis.",
                        max_digits=6,
                    ),
                ),
                (
                    "estimated_operational_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Business owner's estimated operational cost of delivering to this zone (fuel, driver wages, vehicle maintenance, packaging, and other delivery overhead, combined into one figure for v1).",
                        max_digits=10,
                    ),
                ),
                (
                    "estimated_delivery_time_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Estimated time to complete a delivery to this zone",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Delivery Zone",
                "verbose_name_plural": "Delivery Zones",
                "ordering": ["zone_name"],
            },
        ),
    ]
