# Generated by Django 5.2.15 on 2026-07-09 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ecommerce", "0002_onlinecustomer_last_purchase_date_and_more"),
        ("products", "0002_product_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding_vector",
                    models.JSONField(
                        help_text="CLIP embedding stored as a list of floats"
                    ),
                ),
                ("model_version", models.CharField(max_length=100)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visual_embedding",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisualSearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_image",
                    models.ImageField(upload_to="visual_search_queries/%Y/%m/"),
                ),
                (
                    "matched_products",
                    models.JSONField(
                        help_text="Snapshot of returned matches: [{'product_id': int, 'similarity_score': float}, ...]"
                    ),
                ),
                ("top_match_confidence", models.FloatField(blank=True, null=True)),
                ("model_version", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("was_helpful", models.BooleanField(blank=True, null=True)),
                ("feedback_notes", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visual_search_queries",
                        to="ecommerce.onlinecustomer",
                    ),
                ),
            ],
        ),
    ]
