from django.db import models
from products.models import Product
from forecasting.models import DemandForecast


class Recommendation(models.Model):
    """
    A persisted, actionable business recommendation generated by the
    AI Advisor from a product's latest forecast, current stock, and
    unmet demand signals (CustomerRequest). Kept in the DB (not
    computed on-the-fly) so it can be linked to notifications, tracked
    for effectiveness, and later read aloud by the Krio Voice Advisor.
    """

    PRIORITY_CRITICAL = 'critical'
    PRIORITY_HIGH = 'high'
    PRIORITY_MEDIUM = 'medium'
    PRIORITY_LOW = 'low'

    PRIORITY_CHOICES = [
        (PRIORITY_CRITICAL, 'Critical'),
        (PRIORITY_HIGH, 'High'),
        (PRIORITY_MEDIUM, 'Medium'),
        (PRIORITY_LOW, 'Low'),
    ]

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='recommendations'
    )
    forecast = models.ForeignKey(
        DemandForecast, on_delete=models.CASCADE, related_name='recommendations'
    )
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES)
    message = models.TextField()
    recommended_action = models.CharField(max_length=255)

    is_actioned = models.BooleanField(default=False)
    actioned_at = models.DateTimeField(null=True, blank=True)

    generated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-generated_at']
        indexes = [
            models.Index(fields=['product', '-generated_at']),
            models.Index(fields=['priority', 'is_actioned']),
        ]

    def __str__(self):
        return f"[{self.get_priority_display()}] {self.product.product_name} — {self.recommended_action}"