from django.db import models
from products.models import Product
from forecasting.models import DemandForecast


class Recommendation(models.Model):
    """
    A persisted, actionable business recommendation generated by the
    AI Advisor from a product's latest forecast, current stock, and
    unmet demand signals (CustomerRequest). Kept in the DB (not
    computed on-the-fly) so it can be linked to notifications, tracked
    for effectiveness, and later read aloud by the Krio Voice Advisor.
    """

    PRIORITY_CRITICAL = 'critical'
    PRIORITY_HIGH = 'high'
    PRIORITY_MEDIUM = 'medium'
    PRIORITY_LOW = 'low'

    PRIORITY_CHOICES = [
        (PRIORITY_CRITICAL, 'Critical'),
        (PRIORITY_HIGH, 'High'),
        (PRIORITY_MEDIUM, 'Medium'),
        (PRIORITY_LOW, 'Low'),
    ]

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='recommendations'
    )
    forecast = models.ForeignKey(
        DemandForecast, on_delete=models.CASCADE, related_name='recommendations'
    )
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES)
    message = models.TextField()
    recommended_action = models.CharField(max_length=255)

    is_actioned = models.BooleanField(default=False)
    actioned_at = models.DateTimeField(null=True, blank=True)

    confidence_score = models.FloatField(
        null=True, blank=True,
        help_text="0.0-1.0. How confident the advisor is in this recommendation, "
                   "based on forecast confidence, data sufficiency, and signal strength."
    )
    confidence_reasons = models.JSONField(
        default=list, blank=True,
        help_text="List of short strings explaining what drove the confidence score, "
                   "e.g. ['Forecast available', 'Sales trend increasing', 'Stock below reorder point']"
    )

    generated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-generated_at']
        indexes = [
            models.Index(fields=['product', '-generated_at']),
            models.Index(fields=['priority', 'is_actioned']),
        ]

    def __str__(self):
        return f"[{self.get_priority_display()}] {self.product.product_name} — {self.recommended_action}"

class AdvisorConversationSession(models.Model):
    """
    A single multi-turn conversation between a staff member and the AI
    Business Advisor's conversational layer (Step 19). Staff-scoped —
    completely separate from ai_commerce.ConversationSession, which is
    customer-facing. Mirrors that model's structure (context_state for
    slot-filling, append-only turns) but with staff auth instead.
    """
    staff_user = models.ForeignKey(
        'accounts.CustomUser',
        on_delete=models.CASCADE,
        related_name='advisor_conversation_sessions',
    )
    context_state = models.JSONField(default=dict, blank=True)
    started_at = models.DateTimeField(auto_now_add=True)
    last_message_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-last_message_at']
        verbose_name = 'Advisor Conversation Session'
        verbose_name_plural = 'Advisor Conversation Sessions'

    def __str__(self):
        return f"{self.staff_user.username} — started {self.started_at:%Y-%m-%d %H:%M}"


class AdvisorConversationTurn(models.Model):
    """
    Append-only log of a single message within an AdvisorConversationSession.
    Same pattern as ai_commerce.ConversationTurn — intent_detected and
    routed_to record which read-only module function actually answered
    the question, for transparency and dissertation evidence that this
    is genuine orchestration, not reimplemented logic.
    """
    ROLE_CHOICES = [
        ('staff', 'Staff'),
        ('assistant', 'Assistant'),
    ]

    session = models.ForeignKey(
        AdvisorConversationSession, on_delete=models.CASCADE, related_name='turns'
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    message_text = models.TextField()
    intent_detected = models.CharField(max_length=50, blank=True)
    routed_to = models.CharField(max_length=50, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['session', 'created_at']
        verbose_name = 'Advisor Conversation Turn'
        verbose_name_plural = 'Advisor Conversation Turns'
        indexes = [models.Index(fields=['session', 'created_at'])]

    def __str__(self):
        preview = self.message_text[:50] + ('...' if len(self.message_text) > 50 else '')
        return f"[{self.get_role_display()}] {preview}"