# Generated by Django 5.2.15 on 2026-07-08 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        editable=False,
                        help_text="Defines chain order. Assigned automatically in services.create_ledger_entry().",
                        unique=True,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("online_order_confirmation", "Online Order Confirmation"),
                            ("payment_confirmation", "Payment Confirmation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "record_reference",
                    models.CharField(
                        help_text="Human-readable reference to the source record, e.g. an OnlineOrder.order_reference",
                        max_length=100,
                    ),
                ),
                (
                    "payload_snapshot",
                    models.JSONField(
                        help_text="JSON snapshot of the critical fields being verified at the time of the event"
                    ),
                ),
                ("previous_hash", models.CharField(max_length=64)),
                (
                    "current_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Ledger Entry",
                "verbose_name_plural": "Ledger Entries",
                "ordering": ["sequence_number"],
            },
        ),
    ]
