# Generated by Django 5.2.15 on 2026-07-03 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
        ("ecommerce", "0001_initial"),
        ("products", "0002_product_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinecustomer",
            name="last_purchase_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onlinecustomer",
            name="lifetime_spending",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Cumulative total of all confirmed order amounts",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="onlinecustomer",
            name="preferred_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="System-computed top purchase categories, refreshed on each confirmed order",
                related_name="preferred_by_customers",
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="onlinecustomer",
            name="total_orders",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="onlinecustomer",
            name="trust_score",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Rule-based trust score (0-100), auto-updated on each confirmed order. See ecommerce.services.calculate_trust_score().",
            ),
        ),
        migrations.AddField(
            model_name="onlineorder",
            name="delivery_distance_km",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Distance used to calculate delivery_fee at checkout time",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="onlineorder",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="onlineorder",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("own_rider", "Own Rider"),
                    ("third_party", "Third-Party Courier"),
                    ("customer_pickup", "Customer Pickup"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="onlineorder",
            name="delivery_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="onlineorder",
            name="delivery_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assigned", "Assigned"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                ],
                help_text="Tracks the delivery leg specifically, independent of overall order status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="onlineorder",
            name="delivery_zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Zone selected at checkout; determines delivery_fee",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="delivery.deliveryzone",
            ),
        ),
    ]
