# Generated by Django 5.2.15 on 2026-07-21 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_onlinecustomer_last_purchase_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditRepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction_hash", models.CharField(blank=True, max_length=256)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_repayments",
                        to="ecommerce.onlinecustomer",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_credit_repayments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Repayment",
                "verbose_name_plural": "Credit Repayments",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
