# Generated by Django 5.2.15 on 2026-07-23 21:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_creditrepayment"),
        ("products", "0002_product_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineorder",
            name="customer_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the customer confirmed receipt via 'I Received My Order'.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DeliveryReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(help_text="1-5 stars")),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_reviews",
                        to="ecommerce.onlinecustomer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_review",
                        to="ecommerce.onlineorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Review",
                "verbose_name_plural": "Delivery Reviews",
                "ordering": ["-created_at"],
                "unique_together": {("customer", "order")},
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(help_text="1-5 stars")),
                ("review_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to="ecommerce.onlinecustomer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to="ecommerce.onlineorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Review",
                "verbose_name_plural": "Product Reviews",
                "ordering": ["-created_at"],
                "unique_together": {("customer", "product", "order")},
            },
        ),
    ]
