# Generated by Django 5.2.15 on 2026-07-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_onlineorder_customer_confirmed_at_deliveryreview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinecustomer",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="customer_avatars/"
            ),
        ),
    ]
