# Generated by Django 5.2.15 on 2026-07-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ecommerce", "0002_onlinecustomer_last_purchase_date_and_more"),
        ("products", "0002_product_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trust_score_snapshot", models.PositiveIntegerField()),
                ("loyalty_tier_snapshot", models.CharField(max_length=20)),
                (
                    "lifetime_spending_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "outstanding_balance_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "recommended_credit_limit",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "eligibility_status",
                    models.CharField(
                        choices=[
                            ("eligible_increase", "Eligible for Increase"),
                            ("maintain", "Maintain Current Limit"),
                            ("review_needed", "Review Needed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reasoning", models.TextField()),
                ("assistant_version", models.CharField(default="v1", max_length=20)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_assessments",
                        to="ecommerce.onlinecustomer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Assessment",
                "verbose_name_plural": "Credit Assessments",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("natural_language", "Natural Language"),
                            ("guided_planner", "Guided Shopping Planner"),
                            ("shop_by_goal", "Shop by Goal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raw_query", models.TextField(blank=True, null=True)),
                (
                    "parsed_intent",
                    models.JSONField(
                        blank=True,
                        help_text="Structured intent extracted from raw_query before candidate filtering.",
                        null=True,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Soft preference for ranking, never a hard filter.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("family_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "shopping_purpose",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "quality_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("budget", "Budget"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("save_money", "Save Money"),
                            ("premium_quality", "Premium Quality"),
                            ("healthy_living", "Healthy Living"),
                            ("party_shopping", "Party Shopping"),
                            ("weekly_groceries", "Weekly Groceries"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_sessions",
                        to="ecommerce.onlinecustomer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopping Session",
                "verbose_name_plural": "Shopping Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        help_text="Display order within the session's basket."
                    ),
                ),
                (
                    "reasoning",
                    models.TextField(
                        help_text="Claude's human-readable explanation for this pick."
                    ),
                ),
                (
                    "match_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Internal ranking score from the candidate-filtering stage.",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="AI's confidence in this recommendation, 0.0-1.0.",
                    ),
                ),
                (
                    "assistant_version",
                    models.CharField(
                        default="v1",
                        help_text="Identifies which prompt/assistant version generated this row.",
                        max_length=20,
                    ),
                ),
                ("added_to_cart", models.BooleanField(default=False)),
                (
                    "was_helpful",
                    models.BooleanField(
                        blank=True,
                        help_text="Customer feedback. Null means no feedback was given.",
                        null=True,
                    ),
                ),
                ("feedback_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to="products.product",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="ai_commerce.shoppingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopping Recommendation",
                "verbose_name_plural": "Shopping Recommendations",
                "ordering": ["session", "rank"],
                "indexes": [
                    models.Index(
                        fields=["session", "rank"],
                        name="ai_commerce_session_6f5f06_idx",
                    )
                ],
            },
        ),
    ]
