# Generated by Django 5.2.15 on 2026-07-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_commerce", "0001_initial"),
        ("ecommerce", "0002_onlinecustomer_last_purchase_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Accumulated slot-filled context across turns, e.g. {'budget': 15000, 'occasion': 'party', 'dietary': 'no pork'}",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullable — guest conversations are supported, same as CustomerEvent.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_sessions",
                        to="ecommerce.onlinecustomer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Session",
                "verbose_name_plural": "Conversation Sessions",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Customer"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("message_text", models.TextField()),
                ("intent_detected", models.CharField(blank=True, max_length=50)),
                ("routed_to", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="ai_commerce.conversationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Turn",
                "verbose_name_plural": "Conversation Turns",
                "ordering": ["session", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="ai_commerce_session_cb8131_idx",
                    )
                ],
            },
        ),
    ]
