# Generated by Django 5.2.15 on 2026-07-06 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ecommerce", "0002_onlinecustomer_last_purchase_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("shopping_assistant", "AI Shopping Assistant"),
                            ("credit_loyalty", "Smart Credit & Loyalty Assistant"),
                            ("advisor_recap", "AI Business Advisor Recap"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "raw_transcript",
                    models.TextField(
                        help_text="Raw text produced by the browser's SpeechRecognition API."
                    ),
                ),
                (
                    "recognition_language",
                    models.CharField(
                        default="en-US",
                        help_text="Snapshot of the recognition language used for this interaction.",
                        max_length=10,
                    ),
                ),
                (
                    "response_language",
                    models.CharField(
                        default="en",
                        help_text="Snapshot of the response language used for this interaction.",
                        max_length=10,
                    ),
                ),
                (
                    "routed_to",
                    models.CharField(
                        help_text="Name of the existing service function this transcript was routed to.",
                        max_length=100,
                    ),
                ),
                (
                    "response_summary",
                    models.TextField(
                        help_text="The narrated text that was actually spoken back to the user."
                    ),
                ),
                (
                    "was_successful",
                    models.BooleanField(
                        blank=True,
                        help_text="Nullable: unset until manually reviewed/marked during testing.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for shopping_assistant and credit_loyalty interactions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_interactions",
                        to="ecommerce.onlinecustomer",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for advisor_recap interactions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
