# Generated by Django 5.2.15 on 2026-07-02 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forecasting", "0001_initial"),
        ("products", "0002_product_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("recommended_action", models.CharField(max_length=255)),
                ("is_actioned", models.BooleanField(default=False)),
                ("actioned_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="forecasting.demandforecast",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-generated_at"],
                        name="advisor_rec_product_cb9741_idx",
                    ),
                    models.Index(
                        fields=["priority", "is_actioned"],
                        name="advisor_rec_priorit_e32beb_idx",
                    ),
                ],
            },
        ),
    ]
