# Generated by Django 5.2.15 on 2026-07-19 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advisor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="confidence_reasons",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of short strings explaining what drove the confidence score, e.g. ['Forecast available', 'Sales trend increasing', 'Stock below reorder point']",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="confidence_score",
            field=models.FloatField(
                blank=True,
                help_text="0.0-1.0. How confident the advisor is in this recommendation, based on forecast confidence, data sufficiency, and signal strength.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AdvisorConversationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context_state", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisor_conversation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Advisor Conversation Session",
                "verbose_name_plural": "Advisor Conversation Sessions",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="AdvisorConversationTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("staff", "Staff"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("message_text", models.TextField()),
                ("intent_detected", models.CharField(blank=True, max_length=50)),
                ("routed_to", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="advisor.advisorconversationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advisor Conversation Turn",
                "verbose_name_plural": "Advisor Conversation Turns",
                "ordering": ["session", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="advisor_adv_session_5a8a8b_idx",
                    )
                ],
            },
        ),
    ]
