# Generated by Django 5.2.15 on 2026-07-02 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_period_start", models.DateField()),
                ("forecast_period_end", models.DateField()),
                (
                    "predicted_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "historical_average",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("increasing", "Increasing"),
                            ("stable", "Stable"),
                            ("decreasing", "Decreasing"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="0-100 confidence score derived from model fit (R²).",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "recommended_restock_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="max(0, predicted_quantity - current_stock) at time of generation.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("has_sufficient_data", models.BooleanField(default=True)),
                (
                    "insufficient_data_message",
                    models.CharField(blank=True, max_length=255),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.CharField(default="v1.0-linreg", max_length=20),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demand Forecast",
                "verbose_name_plural": "Demand Forecasts",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-generated_at"],
                        name="forecasting_product_076acf_idx",
                    )
                ],
            },
        ),
    ]
